apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: nlu-ambiverse
  labels:
    app: neo4j
    component: core
spec:
  selector:
    app: neo4j
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: https
      protocol: TCP
      port: 7473
      targetPort: 7473
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  
