apiVersion: v1
kind: Service
metadata:
  name: nlu
  namespace: nlu-ambiverse
  labels:
    app: nlu
spec:
  type: LoadBalancer
  selector:
    app: nlu
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
