apiVersion: v1
kind: Service
metadata:
  name: knowledgegraph
  namespace: nlu-ambiverse
  labels:
    app: knowledgegraph
spec:
  type: LoadBalancer
  selector:
    app: knowledgegraph
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
